name: Release

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Install dependencies
      run: npm ci

    - name: Build native module
      run: npm run build

    - name: Run tests
      run: |
        npm test
        npm run test-families
        npm run test-lazy

    - name: Release
      uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        package-name: apriltag-node
        changelog-types: |
          [
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"perf","section":"Performance Improvements","hidden":false},
            {"type":"deps","section":"Dependencies","hidden":false},
            {"type":"revert","section":"Reverts","hidden":false},
            {"type":"docs","section":"Documentation","hidden":true},
            {"type":"style","section":"Styles","hidden":true},
            {"type":"chore","section":"Miscellaneous","hidden":true},
            {"type":"refactor","section":"Refactoring","hidden":true},
            {"type":"test","section":"Tests","hidden":true},
            {"type":"build","section":"Build System","hidden":true},
            {"type":"ci","section":"CI/CD","hidden":true}
          ]